import React from "react";
import "./cn-footer.css";

export function FooterCN() {
	return (
		<footer>
			<hr />
			<div className='footer'>
				<a
					className='social-a'
					href={
						"https://open.spotify.com/show/3eBLAu72smJr1GYHHEdanN?si=5ea4ea401d494953&nd=1&dlsi=0f31c92a1bd4490a"
					}
					target='_blank'>
					<img
						src={"/assets/social-icons/spotify.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={
						"https://podcasts.apple.com/us/podcast/casa-nostra/id1724181171?ign-itscg=30200&ign-itsct=lt_p"
					}
					target='_blank'>
					<img
						src={"/assets/social-icons/apple-podcasts.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={
						"https://music.amazon.es/podcasts/edbda4a8-2813-4f9a-bb6c-53f6fdba13bf/casa-nostra"
					}
					target='_blank'>
					<img
						src={"/assets/social-icons/amazon-music.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={
						"https://music.youtube.com/playlist?list=PLSd-24aOoJHGAsvqxG_SV12geT5TaagdN"
					}
					target='_blank'>
					<img
						src={"/assets/social-icons/youtube-music.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={"https://www.ivoox.com/podcast-casa-nostra_sq_f12354445_1.html"}
					target='_blank'>
					<img
						src={"/assets/social-icons/ivoox.svg"}
						alt=''
					/>
				</a>
				<p>&copy; mimuogi {new Date().getFullYear()}</p>

				<a
					className='social-a'
					href={"https://x.com/CasaNostraPod"}
					target='_blank'>
					<img
						src={"/assets/social-icons/twitter-block.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={"https://www.tiktok.com/@casanostra_lliria"}
					target='_blank'>
					<img
						src={"/assets/social-icons/tiktok.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={"https://www.facebook.com/profile.php?id=61554899325515"}
					target='_blank'>
					<img
						src={"/assets/social-icons/facebook-sq.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={"https://www.instagram.com/lliria.casanostra"}
					target='_blank'>
					<img
						src={"/assets/social-icons/instagram.svg"}
						alt=''
					/>
				</a>
				<a
					className='social-a'
					href={"https://www.youtube.com/channel/UCokSBFzdENFsuj_dKhcuKnA"}
					target='_blank'>
					<img
						src={"/assets/social-icons/youtube.svg"}
						alt=''
					/>
				</a>
			</div>
		</footer>
	);
}
